### PR TITLE
Android 14 fix

### LINKED ISSUE #70: [BUG] Android 14 SecurityException Specify RECEIVER_EXPORTED
App does not work on Android 14 devices.
```
targetSdkVersion 34
compileSdkVersion 34
```

### PR DESCRIPTION
**Pull request by AlexanderThiele**
Error: SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

closes #70

### CODE REVIEW

**Review by Letalus — APPROVED** [review]

**Comment by tairoroberto** [comment]
Waiting for the PR.

**Comment by TarunPal3551** [comment]
is it resolved ? we are also facing same issue in our apps

E/AndroidRuntime(16970): java.lang.SecurityException: app.apnabillbook.com: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(16970): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
E/AndroidRuntime(16970): 	at android.os.Parcel.createException(Parcel.java:3071)
E/AndroidRuntime(16970): 	at android.os.Parcel.readException(Parcel.java:3054)
E/AndroidRuntime(16970): 	at android.os.Parcel.readException(Parcel.java:2996)
E/AndroidRuntime(16970): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
E/AndroidRuntime(16970): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1868)
E/AndroidRuntime(16970): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1804)
E/AndroidRuntime(16970): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
E/AndroidRuntime(16970): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:765)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin.registerSmsRetrieverBroadcastReceiver(OTPPlugin.kt:204)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin.access$registerSmsRetrieverBroadcastReceiver(OTPPlugin.kt:41)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin$listenRetriever$1.invoke(OTPPlugin.kt:164)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin$listenRetriever$1.invoke(OTPPlugin.kt:164)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin.listenRetriever$lambda$2(OTPPlugin.kt:164)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin.$r8$lambda$M0eR2oxFk9TVpDz4SIjN-L_lMQ4(Unknown Source:0)
E/AndroidRuntime(16970): 	at ru.surfstudio.otp_autofill.OTPPlugin$$ExternalSyntheticLambda0.onSuccess(Unknown Source:2)
E/AndroidRuntime(16970): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(16970): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(16970): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16970): 	at android.os.Looper.loopOnce(Looper.java:257)
E/AndroidRuntime(16970): 	at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(16970): 	at android.app.ActivityThread.main(ActivityThread.java:8826)
E/AndroidRuntime(16970): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16970): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(16970): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(16970): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(16970): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14887)
E/AndroidRuntime(16970): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
E/AndroidRuntime(16970): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3005)
E/AndroidRuntime(16970): 	at android.os.Binder.execTransactInternal(Binder.java:1387)
E/AndroidRuntime(16970): 	at android.os.Binder.execTransact(Binder.java:1299)
E/AndroidRuntime(16970):

**Comment by AlexanderThiele** [comment]
no, they merged the wrong PR 🙈

**Comment by DmitrDomrachev** [comment]
https://github.com/surfstudio/flutter-otp-autofill/pull/72

**Pull request closed without merging**
